trellis-ldp/trellis-extensions

- app/src/main/java/org/trellisldp/ext/app/db/AppConfiguration.java
as suggested to allow external ITs with DropwizardTestSupport.
> makes AppConfiguration public

- app/src/main/java/org/trellisldp/ext/app/db/TrellisApplication.java
- app/src/test/resources/trellis-config.yml
- deployment/src/dist/etc/config.yml
Related to #9 
@gregjan will these ENV overrides work for you?
> Add ENV overrides for default configuration file

- db/src/main/java/org/trellisldp/ext/db/DBResource.java
- db/src/main/java/org/trellisldp/ext/db/DBResourceService.java
- db/src/test/java/org/trellisldp/ext/db/DBResourceTest.java
- db/src/test/java/org/trellisldp/ext/db/ResourceDataTest.java
Related to trellis-ldp/trellis#407
> Add config for adding LDP ixn model to RDF bodies

- .appveyor.yml
- .travis.yml
- app/build.gradle
- build.gradle
- db/build.gradle
- db/src/main/java/org/trellisldp/ext/db/DBHealthCheck.java
- db/src/main/java/org/trellisldp/ext/db/DBNamespaceService.java
- db/src/main/java/org/trellisldp/ext/db/DBResourceService.java
- db/src/main/java/org/trellisldp/ext/db/DBWrappedMementoService.java
- db/src/main/resources/META-INF/beans.xml
- settings.gradle
- webapp/build.gradle
- webapp/src/main/java/org/trellisldp/ext/db/webapp/AuthorizationCache.java
- webapp/src/main/java/org/trellisldp/ext/db/webapp/CDIConstraintServices.java
- webapp/src/main/java/org/trellisldp/ext/db/webapp/ProfileCache.java
- webapp/src/main/java/org/trellisldp/ext/db/webapp/ServiceProducers.java
- webapp/src/main/java/org/trellisldp/ext/db/webapp/TrellisApplication.java
- webapp/src/main/java/org/trellisldp/ext/db/webapp/TrellisCache.java
- webapp/src/main/java/org/trellisldp/ext/db/webapp/package-info.java
- webapp/src/main/resources/META-INF/beans.xml
- webapp/src/main/resources/application.properties
- webapp/src/main/resources/db/migration/V0.3__Trellis.sql
- webapp/src/test/java/org/trellisldp/ext/db/webapp/AbstractApplicationTests.java
- webapp/src/test/java/org/trellisldp/ext/db/webapp/EmbeddedPgsqlApplicationTest.java
- webapp/src/test/java/org/trellisldp/ext/db/webapp/PgsqlApplicationTest.java
Add a quarkus-based (microprofile) deployment option.
> Add a Microprofile-based deployment option

- aws/build.gradle
- aws/src/main/java/org/trellisldp/ext/aws/DefaultNamespaceService.java
- aws/src/main/java/org/trellisldp/ext/aws/S3Binary.java
- aws/src/main/java/org/trellisldp/ext/aws/S3BinaryService.java
- aws/src/main/java/org/trellisldp/ext/aws/S3MementoService.java
- aws/src/main/java/org/trellisldp/ext/aws/S3Resource.java
- aws/src/main/java/org/trellisldp/ext/aws/SNSEventService.java
- aws/src/main/java/org/trellisldp/ext/aws/package-info.java
- aws/src/main/resources/META-INF/beans.xml
- aws/src/main/resources/META-INF/services/org.trellisldp.api.BinaryService
- aws/src/main/resources/META-INF/services/org.trellisldp.api.MementoService
- aws/src/test/java/org/trellisldp/ext/aws/DefaultNamespaceServiceTest.java
- aws/src/test/java/org/trellisldp/ext/aws/S3BinaryServiceTest.java
- aws/src/test/java/org/trellisldp/ext/aws/S3MementoServiceTest.java
- aws/src/test/java/org/trellisldp/ext/aws/SNSEventServiceTest.java
- aws/src/test/resources/META-INF/microprofile-config.properties
- aws/src/test/resources/file.txt
- aws/src/test/resources/logback-test.xml
- build.gradle
- buildtools/src/main/resources/pmd/pmd.xml
- buildtools/src/main/resources/spotbugs/exclusions.xml
- platform/bom/build.gradle
- settings.gradle
This migrates the code from https://github.com/trellis-ldp/trellis-ext-aws into this repository, which will allow us to consolidate all of the extensions into a single repository.
> Migrate AWS component into extensions repository

- build.gradle
- platform/quarkus/build.gradle
- platform/quarkus/src/main/resources/application.properties
This updates quarkus to the latest version and adds support for fully assembled images
> Update quarkus, build runnable image

- .travis.yml
This is a test to see if oraclejdk11 works better with the gradle plugins repository
> Change jdk11 for CI

- aws/src/main/java/org/trellisldp/ext/aws/S3MementoService.java
- db/build.gradle
- db/src/main/java/org/trellisldp/ext/db/DBUtils.java
- db/src/main/java/org/trellisldp/ext/db/DBWrappedMementoService.java
- db/src/test/java/org/trellisldp/ext/db/DBUtilsTest.java
- db/src/test/java/org/trellisldp/ext/db/DBWrappedMementoServiceTest.java
Related to trellis-ldp/trellis#600
> Update memento CDI annotations

- .travis.yml
- aws/build.gradle
- aws/src/main/java/org/trellisldp/ext/aws/S3BinaryService.java
- aws/src/main/java/org/trellisldp/ext/aws/S3MementoService.java
- aws/src/main/java/org/trellisldp/ext/aws/SNSEventService.java
- aws/src/test/java/org/trellisldp/ext/aws/S3BinaryServiceTest.java
- aws/src/test/java/org/trellisldp/ext/aws/S3MementoServiceTest.java
- aws/src/test/java/org/trellisldp/ext/aws/SNSEventServiceTest.java
- aws/src/test/resources/META-INF/microprofile-config.properties
- cassandra/README.md
- cassandra/build.gradle
- cassandra/src/test/java/org/trellisldp/ext/cassandra/CassandraBinaryServiceIT.java
- cassandra/src/test/java/org/trellisldp/ext/cassandra/CassandraContextIT.java
- cassandra/src/test/java/org/trellisldp/ext/cassandra/CassandraMementoServiceIT.java
- cassandra/src/test/java/org/trellisldp/ext/cassandra/CassandraResourceServiceIT.java
- db/build.gradle
- db/src/main/java/org/trellisldp/ext/db/DBResourceService.java
- db/src/test/resources/META-INF/microprofile-config.properties
- platform/dropwizard/src/main/resources/META-INF/microprofile-config.properties
- platform/quarkus/build.gradle
- platform/quarkus/src/main/java/org/trellisldp/ext/webapp/AuthorizationCache.java
- platform/quarkus/src/main/java/org/trellisldp/ext/webapp/ProfileCache.java
- platform/quarkus/src/main/resources/application.properties
- platform/quarkus/src/test/java/org/trellisldp/ext/webapp/CassandraApplicationTest.java
- platform/quarkus/src/test/java/org/trellisldp/ext/webapp/CassandraLdpBasicContainmentTest.java
- platform/quarkus/src/test/java/org/trellisldp/ext/webapp/CassandraLdpBinaryTest.java
- platform/quarkus/src/test/java/org/trellisldp/ext/webapp/CassandraLdpRdfTest.java
- platform/quarkus/src/test/java/org/trellisldp/ext/webapp/CassandraMementoBinaryTest.java
- platform/quarkus/src/test/java/org/trellisldp/ext/webapp/CassandraMementoRdfTest.java
- platform/quarkus/src/test/java/org/trellisldp/ext/webapp/CassandraMementoTimeMapTest.java
Related to trellis-ldp/trellis#606
Note: this build will fail until the upstream PR is merged
> Normalize configuration properties

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- platform/bom/build.gradle
- settings.gradle
Related to https://github.com/trellis-ldp/trellis/issues/625
> Upgrade to gradle 6

- settings.gradle
This makes the dependabot integration work much better.
> Adjust settings file format for dependabot integration

- build.gradle
> Revert datastax driver update

- platform/dropwizard/src/main/java/org/trellisldp/ext/db/app/AppUtils.java
Related to trellis-ldp/trellis#691
> Use package whitelist for ActiveMQ object serialization

- db/build.gradle
- db/src/main/java/org/trellisldp/ext/db/DBResource.java
- db/src/main/java/org/trellisldp/ext/db/DBResourceService.java
- db/src/main/resources/db/migration/V0.4__Trellis.sql
- db/src/main/resources/migrations.yml
- db/src/test/java/org/trellisldp/ext/db/DBResourceTest.java
- db/src/test/java/org/trellisldp/ext/db/ResourceDataTest.java
This makes it possible to configure arbitrary extension/metadata graphs. This also adds a new table to the database schema.
> Improve resource extension metadata

- .travis.yml
- build.gradle
- platform/quarkus/src/test/java/org/trellisldp/ext/webapp/PgsqlApplicationTest.java
- settings.gradle
Adjust settings for travis tests
> Upgrade quarkus to 1.3

- platform/quarkus/src/test/java/org/trellisldp/ext/webapp/CassandraMementoBinaryTest.java
- platform/quarkus/src/test/java/org/trellisldp/ext/webapp/CassandraMementoRdfTest.java
Resolves https://github.com/trellis-ldp/trellis/issues/563
> Remove memento test overrides

- platform/quarkus/build.gradle
> Update h2 dependency

- build.gradle
- platform/quarkus/build.gradle
> Bump netty to 4.1.48.Final

- db/src/main/java/org/trellisldp/ext/db/DBResource.java
- db/src/main/java/org/trellisldp/ext/db/DBResourceService.java
- db/src/test/java/org/trellisldp/ext/db/DBResourceTest.java
> Allow disabling direct/indirect container support

- build.gradle
- platform/quarkus/build.gradle
This will significantly simplify how quarkus artifacts are built.
> Simplify quarkus build configuration

- platform/quarkus/src/main/java/org/trellisldp/ext/quarkus/AuthorizationCache.java
- platform/quarkus/src/main/java/org/trellisldp/ext/quarkus/ProfileCache.java
- platform/quarkus/src/main/java/org/trellisldp/ext/quarkus/TrellisApplication.java
- platform/quarkus/src/main/java/org/trellisldp/ext/quarkus/package-info.java
- platform/quarkus/src/test/java/org/trellisldp/ext/quarkus/AbstractApplicationTests.java
- platform/quarkus/src/test/java/org/trellisldp/ext/quarkus/CassandraApplicationTest.java
- platform/quarkus/src/test/java/org/trellisldp/ext/quarkus/CassandraLdpTest.java
> Rename package in quarkus project

- aws/src/test/java/org/trellisldp/ext/aws/S3BinaryServiceTest.java
- aws/src/test/java/org/trellisldp/ext/aws/S3MementoServiceTest.java
- aws/src/test/java/org/trellisldp/ext/aws/SNSEventServiceTest.java
- cassandra/src/test/java/org/trellisldp/ext/cassandra/CassandraBinaryServiceIT.java
Minor tidying up of the test code.
> Test code clean-up

- .github/workflows/cd-config.yml
- .github/workflows/ci-config.yml
This validates the gradle wrapper before invoking it in GH action workflows
> Validate the gradle wrapper

- build.gradle
This cleans up the javadoc generation
> Remove docs task
